### ISSUE TITLE
Problem importing JSON realtimedatabase

### ISSUE THREAD

**Issue by obbila** [firebase/firebase-tools-ui#411]
Previously this has worked fine but most recently when trying to import a JSON export of my realtime database from firebase into the firebase emulator I get an import error. 

Looks like it is some sort of permission error but I do not know why as previously this worked fine for me?

<img width="1753" alt="Screenshot 2020-11-09 at 15 44 45" src="https://user-images.githubusercontent.com/6563072/98565721-d7c6a480-22a5-11eb-83cf-38f617d17866.png">

<img width="922" alt="Screenshot 2020-11-09 at 16 02 53" src="https://user-images.githubusercontent.com/6563072/98565738-ddbc8580-22a5-11eb-9da4-8155d25cd64f.png">

**Comment by yuchenshi** [comment]
We did recently change this, but I don't really see how this could be happening

**Comment by yuchenshi** [comment]
In order to troubleshoot, could you please try these steps?

1. Make sure you are on the latest CLI version
2. Open the Network tab in Chrome DevTools and open it BEFORE you upload the JSON
3. Perform the upload
4. Inspect the upload network request (you can right click and select Copy > request headers and paste it here.)

Thanks!

**Comment by obbila** [comment]
OK looks like updating firebase-tools and npm solved this.

**Comment by obbila** [comment]
thanks
