### ISSUE TITLE
Custom claims missing in local Firebase function

### ISSUE THREAD

**Issue by codechips** [firebase/firebase-tools-ui#424]
I create a user in the local auth emulator and later set custom claims for her later at some stage. 

The claims are set correctly and are also visible in the Firebase emulator when you edit the user.

However, when I try to execute local Firebase function and get the claims from the `context.auth.token`, custom claims are not present for some reason. 

Is this a bug or am I doing something wrong?

### Function that sets custom claims
```
exports.processSignUp = functions.auth.user().onCreate(async user => {
  // ...
  try {
    await firebase.auth().setCustomUserClaims(user.uid, customClaims);
  } catch (err) {
    console.log(err);
  }
  // ...
});
```

### Function that tries to access the claims

```
export const testFunc = functions.https.onCall((data, context) => {
  // custom claims are not present in the token
  console.log(context.auth.token);
  return { ok: false }
});
````

**Comment by yuchenshi** [comment]
Have you re-authenticated on the client side? Same as production, [custom claims are added to new tokens issued AFTER you set them, not existing sessions](https://firebase.google.com/docs/auth/admin/custom-claims#propagate_custom_claims_to_the_client).

What likely happened is that the client creates a new user (getting the initial token without claims), and then `onCreate` triggers which sets the claims on the user. You will then need to reauthenticate or force refresh the token on the client in order to receive a new token with the claims. See docs linked above. Keep in mind that you'll also need to handle this case in production too, not just the emulator.
