### ISSUE TITLE
Android Emulator Crashes when reading from local Firebase.

### ISSUE THREAD

**Issue by ZiyadF296** [firebase/firebase-tools-ui#544]
I have a Flutter app running on my emulator. I have set up Firebase with my app and when connecting to the server, authentication, read/write and all other functions work as expected. However, when I switch to localhost (emulator UI), the app crashes whenever I am requesting a read request from the local Firebase emulator.

Below attached is the logs that are generated:

[firebase-debug.log](https://github.com/firebase/firebase-tools-ui/files/6319095/firebase-debug.log)

**Comment by malcolmdeck** [comment]
Hey @ziyadfarhan296 , it would probably be helpful to have the logs of the application rather than those of the Firebase emulator. It appears that the emulator is working fine, and that something in the application isn't playing nicely. Can you please attach a logcat readout from the Android app as it crashes?

**Comment by ziyadfarhan296** [comment]
Hey!
Not quite sure about the log file you are referring to. I am building my app with Flutter. Do you know where I can get the logs from?
Thank You

**Comment by malcolmdeck** [comment]
You can see how to capture a bug report on an Android device [here](https://developer.android.com/studio/debug/bug-report)

**Comment by ZiyadF296** [comment]
Problem Solved 👍 
Thanks for the help.
