### ISSUE TITLE
Firestore requests tab is unordered making it mostly unusable

### ISSUE THREAD

**Issue by AndrewMorsillo** [firebase/firebase-tools-ui#634]
The requests list at `/firestore/requests` is unordered. This makes it mostly unusable as it's very hard to find new requests as they happen. The page should be ordered by timestamp.

firebase-tools: 9.16.6
platform: MacOS arm64 (M1) 11.5.2
browser: Firefox 92.0b6

**Comment by yuchenshi** [comment]
It should be ordered by timestamp with new requests on the _bottom_. If that's not the case, please provide a bit more information (e.g. screenshots and what requests are performed) for us to repro. If that is the case but you find it confusing, also kindly let us know and we're open to suggestions.

**Comment by AndrewMorsillo** [comment]
@yuchenshi It is completely unordered. New requests appear at a random position in the list. See this screenshot, requests are not ordered by time. 

![image](https://user-images.githubusercontent.com/858965/131861955-1fa85015-ffa2-4cd8-bbf7-2b7958e772f9.png)

**Comment by cristianberroeta** [comment]
I've been able to replicate the issue. I created this repository to debug it:
https://github.com/cristianberroeta/firestore-requests-timestamps-issue-debugging

It looks like this:
![image](https://user-images.githubusercontent.com/17519897/132284926-caca7c8f-3ecc-49e0-b25c-14f49896e472.png)

As I described there, if you press the buttons in this sequence, you should get the issue in the Emulators UI, Firestore Request tab, Time column:
1. Get document
2. Initialize data
3. Get document (apparently, this has to be pressed 1 minute before the previous "Get document", for the issue to happen)

After that, this is what I see in the Firebase UI, Firestore Requests tab, where you can see that the third row has an older value in the Time column than the second one:
![image](https://user-images.githubusercontent.com/17519897/132285250-2d50c840-e01a-4c33-9dc2-0b532c9fa080.png)

The issue seems to be related with the field that is being used for that Time column. As we can see, the objects that we get from the Emulators actually have a time field in the root, and also a time field inside the rulesContext field:
![image](https://user-images.githubusercontent.com/17519897/132285768-ab920cdc-62d8-4dac-af00-42f3fcadc778.png)
![image](https://user-images.githubusercontent.com/17519897/132285817-1c65b939-7e45-4eeb-b03e-5720e41f54c2.png)

Apparently, the rulesContext.time field keeps the timestamp at which some web socket communication was created. In the case of get-only-once firestore requests, that connection seems to last for 1 minute, On the other hand, the root time field seems to have the timestamp at which the request was actually sent.

We are using the rulesContext.time, while I suspect that we should use the root time field. So I added the time field to the FirestoreRulesEvaluation interface, and used that for the Time column. After that, the issue seems to have gone, as it can be seen in the last 2 images.

Please check if this is correct.

**Comment by yuchenshi** [comment]
Thanks for looking into this, @cristianberroeta! There are two separate issues here. First, as you've observed, the top-level `time` field should be used. This should fix the display on the list view discovered by OP @AndrewMorsillo.

There's still an underlying issue as to why `rulesContext.time` is in the past for the third request, which we're looking into right now internally. That part is within the Firestore Emulator, which is not open source.

**Comment by cristianberroeta** [comment]
no problem @yuchenshi.

I also noticed that if you follow these steps:
1. press the button "Start listening for document changes",
2. refresh the page, without pressing "Stop listening for document changes" before (or you can even close the page, and then reopen it in another browser tab),
3. press the button "Update document",

then these are the logged requests:
![image](https://user-images.githubusercontent.com/17519897/132422682-78f0a753-9858-40fc-b7a7-0bca35f44710.png)

I'm not sure if that is the expected behavior, but if you have a website in which you don't clean the listeners and your page is reloaded multiple times, then you can apparently end up with multiple GET requests being sent after an UPDATE, like this:
![image](https://user-images.githubusercontent.com/17519897/132423004-42a084d7-3a5a-4bdb-835d-0848af1013be.png)
