### ISSUE TITLE
Loading firestore UI gets "ERR_CONNECTION_REFUSED" and "Failed to fetch" errors

### ISSUE THREAD

**Issue by pd93** [firebase/firebase-tools-ui#747]
I have the Firebase emulators and UI running via a `Dockerfile` in a local Minikube K8s cluster with TLS configured to terminate at ingress to the cluster. This means that we access the UI at an address like `https://firebase.local.example.com`. However, internally the pods communicate over `http`. I am using the code from #667 to build the image so that `https` is supported. However, I'm still getting errors in my console (see below). I am not sure if they are related to TLS or not.

`Dockerfile`:
```dockerfile
FROM node:16-buster

# Update apt repositories and install the Java JDK/JRE
RUN apt update -y && \
    apt install -y \
    openjdk-11-jre-headless

# Install the firebase suite globally
RUN npm install -g firebase-tools

# Build the UI from a branch
WORKDIR /src
RUN git clone --branch fix/base-url-hardcoded-protocol https://github.com/BobbieGoede/firebase-tools-ui
WORKDIR /src/firebase-tools-ui
RUN npm install
RUN npm run build

# Copy the firebase configuration file
COPY firebase.json /firebase.json

EXPOSE 4000
EXPOSE 8080
EXPOSE 8085
EXPOSE 9099

CMD [ "firebase", "emulators:exec", "--config", "/firebase.json", "--project", "my-project", "--import", "/data/export", "--export-on-exit", "--debug", "HOST=0.0.0.0 PORT=4000 node server.bundle.js" ]
```

`firebase.json`:
```json
{
  "emulators": {
    "ui": {
      "enabled": true,
      "host": "0.0.0.0",
      "port": 4000
    },
    "firestore": {
      "enabled": true,
      "host": "0.0.0.0",
      "port": 8080
    },
    "pubsub": {
      "enabled": true,
      "host": "0.0.0.0",
      "port": 8085
    },
    "auth": {
      "enabled": true,
      "host": "0.0.0.0",
      "port": 9099
    }
  }
}
```
Initially, upon loading the firestore page, I get this view:

![image](https://user-images.githubusercontent.com/9294862/166486749-1222c7ee-7a53-41b6-9375-b6c5708068e8.png)

However, after a few seconds, the page goes blank (white) and the below messages appear in the console:

![image](https://user-images.githubusercontent.com/9294862/166488707-629715e0-515d-4a64-b1ac-d474ab83951a.png)

Executing from within the container:

```shell
# The call being made in the browser console
> curl -X POST 'https://firebase.local.example.com:8080/v1/projects/my-project-id/databases/(default)/documents:listCollectionIds'
curl: (7) Failed to connect to firebase.local.example.com port 8080: Connection refused
```

I would expect the call above to still use `localhost` as opposed to the domain name as we don't need to leave the container to access the emulator:

```shell
# Calling localhost with HTTPS
> curl -X POST 'https://localhost:8080/v1/projects/my-project-id/databases/(default)/documents:listCollectionIds'
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number

# Calling localhost with HTTP
> curl -X POST 'http://localhost:8080/v1/projects/my-project-id/databases/(default)/documents:listCollectionIds'
{"error":{"code":403,"message":"Metadata operations require admin authentication.","status":"PERMISSION_DENIED"}}
```

The last call here fails, but its an auth issue, so maybe a call to localhost with http here would work?

**Comment by yuchenshi** [comment]
> The last call here fails, but its an auth issue, so maybe a call to localhost with http here would work?

When issuing requests to the Firestore Emulator that requires admin authentication, the header `Authorization: Bearer owner` suffices. For example, `curl -X POST -H "Authorization: Bearer owner" 'http://localhost:8080/v1/projects/my-project-id/databases/(default)/documents:listCollectionIds'`

> I would expect the call above to still use localhost as opposed to the domain name as we don't need to leave the container to access the emulator

Let's look at this closely. The Emulator UI web page runs in your _browser_ instead of any container, regardless of pod / container configuration. As a result, your browser, likely running in your host machine (or even a remote machine / a phone over the LAN) will need to reach into the container that runs the Firestore emulator. Therefore, this is drastically different from running `curl` executing within the container. If I understand your setup correctly, any access from outside the cluster then will then require HTTPS.

I'm not exactly familiar with your stack, but I believe if you can somehow set up a TLS termination proxy also for `https://firebase.local.example.com:8080` and any other emulator port you'd like to view from the UI, this should all work together. Alternatively, if you really want all communications to be within the same container, you can also install and run a browser within the same container / cluster using x11docker etc. I personally wouldn't go the second route if I were you though.

**Comment by pd93** [comment]
> runs in your browser

@yuchenshi yep.. my mistake 🤦‍♂️. The issue was that I was simply not exposing firestore, so the UI could not connect. Thanks for the clarification.

The next problem I have is that I tried to expose the firebase UI and firestore on the same ingress resource (and therefore the same hostname), but with different ports, but I'm not sure this is possible with k8s. Another option would be to expose them on separate ingress resources, but this gives them different hostnames and so the address that the UI tries to dial will be incorrect. Is there a way to make the UI at `firebase.local.example.com` dial to `firestore.local.example.com:443`?

**Comment by yuchenshi** [comment]
I'm not an expert on k8s but I'd say making them listen on the same hostname is worth a try. As to using different domain names, unfortunately, the Emulator UI isn't that customizable yet and I can only think of hacks to make that happen. One of such hacks is to run a custom Emulator UI build with modified [`server.js`](https://github.com/firebase/firebase-tools-ui/blob/16d3541c78497e8c4fc3b022f15b2b2c03ae6d69/server.js#L80) adding logic to change the `host` of each emulator.

**Comment by pd93** [comment]
@yuchenshi Thanks. I'll close this for now. I might open another ticket in the future to support k8s deployments if I can't find another way.
