### ISSUE TITLE
emulators:exec --ui unknown option

### ISSUE THREAD

**Issue by criesbeck** [firebase/firebase-tools-ui#750]
### [REQUIRED] Environment info

```
firebase --version
8.6.0
```

```
npm list --global
```

```
├── corepack@0.10.0
├── firebase-tools@10.8.0
└── npm@8.9.0
```

MacOS Big Sur 11.6.5

### [REQUIRED] Test case

```
firebase emulators:exec --ui 'npm start'
```

### [REQUIRED] Steps to reproduce

Run the above command in a React project.

### [REQUIRED] Expected behavior

It should start the emulators, start the local suite UI, and run the React app, as per [the documentation[(https://firebase.google.com/docs/emulator-suite/install_and_configure#startup).

### [REQUIRED] Actual behavior

```
error: unknown option '--ui'
```

Also

```
firebase help emulators:exec
```

does not include a ``--ui`` option.

```
Usage: firebase emulators:exec [options] <script>

start the local Firebase emulators, run a test script, then shut down the emulators

Options:
  --only <emulators>          only specific emulators. This is a comma separated list of emulator names.
                              Valid options are: ["functions","firestore","database","hosting","pubsub"]
  --inspect-functions [port]  emulate Cloud Functions in debug mode with the node inspector on the given
                              port (9229 if not specified)
  --import [dir]              import emulator data from a previous export (see emulators:export)
  --export-on-exit [dir]      automatically export emulator data (emulators:export) when the emulators make
                              a clean exit (SIGINT), when no dir is provided the location of --import [dir]
                              is used
  -h, --help                  output usage information
```

Has the local suite UI been removed?

**Comment by yuchenshi** [comment]
Given that your `firebase --version` shows `8.6.0` (which is an ancient version) and doesn't agree with `npm list --global`, I believe you have more than one version of Firebase CLI installed. Try `which firebase` to locate the executable and resolve this locally. For example, if you have both the standalone binary and `npm` version installed, you'll need to remove the standalone binary. Alternatively, check your `$PATH`.

I'm going to close this issue since this is an issue with local setup.

**Comment by criesbeck** [comment]
Thanks for the quick response and sorry to waste your time.
