### ISSUE TITLE
Firestore is not instantiated in the window object anymore

### ISSUE THREAD

**Issue by MorenoMdz** [firebase/firebase-tools-ui#837]
### [REQUIRED] Environment info

**firebase-tools:** 11.4.1

**Platform:** Mac

### [REQUIRED] Test case

Start the emulator with Firestore
Go into the web console, try to access `firestore` from it

<img width="707" alt="image" src="https://user-images.githubusercontent.com/29472480/182502582-5e40c4da-6de2-4a4c-80c6-d74601813319.png">

### [REQUIRED] Steps to reproduce

Above

### [REQUIRED] Expected behavior

Should be able to access it from the window object in the dev console as usual.

### [REQUIRED] Actual behavior

Firestore is not accessible from the console anymore since v11.2ish

**Comment by christhompsongoogle** [comment]
So this was likely caused by the transition to the modular Javascript SDK in v9. The firebase object is no longer in the global space. See
https://github.com/firebase/firebase-tools-ui/commit/308a98d9a7b0dc3aba3228f701a01719fd3cb870

**Comment by MorenoMdz** [comment]
> So this was likely caused by the transition to the modular Javascript SDK in v9. The firebase object is no longer in the global space. See [308a98d](https://github.com/firebase/firebase-tools-ui/commit/308a98d9a7b0dc3aba3228f701a01719fd3cb870)

Hmm, before we close this, can we make it available again somehow? It is something very useful to have as the queries we can apply from the UI are very limitaded. Feels like a feature regression losing it, and since it is available in the production Firestore console it feels like a feature mismatch as well.

**Comment by MorenoMdz** [comment]
For context, [this](https://github.com/firebase/firebase-tools-ui/commit/308a98d9a7b0dc3aba3228f701a01719fd3cb870#diff-23a272f4ea30a2768def13877d5e82dd752fbd707452e2b4ad192e2f9a2e4f91L65) could be easily re-enabled right?

**Comment by yuchenshi** [comment]
@MorenoMdz I've discussed this with @christhompsongoogle and a few other colleagues. As much as we'd like to retain this feature, it is technically hard (and near infeasible). While we can still expose the `app` object or the `firestore` object, those will be near useless without the free-floating functions like `doc(firestore, 'a/b')` in modular v9 SDK. Chaining from `firestore.collection('....').doc('...')` is no longer possible in the new v9 SDK syntax. While I cannot speak for the Firebase Console team, the deprecation of v8 SDK is in place and moving towards the new syntax is inevitable in the long run. Not shipping the whole SDK also allows us to vastly reduce the bundle size (and therefore the download / loading time of Emulator UI, and maybe Console in the future.)

With that being said, we're open to ideas to reimplement this feature within the new constraints. And who knows, maybe your idea can help us keep this feature in the Console as well. Also, just a friendly reminder that the Emulator UI is an open source project and we welcome PRs and discussions at any time. While we're closing this issue due to reasons above, the comment thread is still open -- it only takes one good PR or suggestion to continue the discussion. "Can we make it available again somehow"? Well, let's talk about "how" :) .

**Comment by MorenoMdz** [comment]
> @MorenoMdz I've discussed this with @christhompsongoogle and a few other colleagues. As much as we'd like to retain this feature, it is technically hard (and near infeasible). While we can still expose the `app` object or the `firestore` object, those will be near useless without the free-floating functions like `doc(firestore, 'a/b')` in modular v9 SDK. Chaining from `firestore.collection('....').doc('...')` is no longer possible in the new v9 SDK syntax. While I cannot speak for the Firebase Console team, the deprecation of v8 SDK is in place and moving towards the new syntax is inevitable in the long run. Not shipping the whole SDK also allows us to vastly reduce the bundle size (and therefore the download / loading time of Emulator UI, and maybe Console in the future.)
> 
> With that being said, we're open to ideas to reimplement this feature within the new constraints. And who knows, maybe your idea can help us keep this feature in the Console as well. Also, just a friendly reminder that the Emulator UI is an open source project and we welcome PRs and discussions at any time. While we're closing this issue due to reasons above, the comment thread is still open -- it only takes one good PR or suggestion to continue the discussion. "Can we make it available again somehow"? Well, let's talk about "how" :) .

Got it, it does make sense. To be honest, there are other ways something similar could be achieved, for example, improvements to the query UI in the emulator is a good example, not just for the emulator UI but for the FB console as well, we tend to use the FS to play with data locally because we can only use one simple query at a time in emulator UI ><
